### ISSUE TITLE
Make mobs combative allies

### ISSUE THREAD

**Issue by Darkmega18** [Micmu/micwands#1]
As an expansion to this mod can you have a wand that makes a mob a "follower/pet"? In that they won't be pacified, and they'll follow you but can fight other mobs with a command? Such as a staff (or from the same staff with a different command) that allows you to tell following mobs to attack other mobs by throwing a projectile out of it and hitting the desired target? or if you hit an already following mob with the targetting projectile it sets it aggressive where it'll just fight enemy mobs that comes too near?

Possibly an optional limitation to this wand and possibly the pacification wand can be having to reduce the mobs health to a percentage or set amount before it works but then they restore all their health when they become a friendly follower/pet?

A wand that could go with it is a wand to open basically a little gui that you can outfit your follower mobs with and hand them potion bottles into another smaller inventory to outfit them instead with potion buffs that work permanently based on what potions you give them. and if they're humanoid like skelly, stray, husk and zombie they can get a bow to do ranged AI or a shield which makes them occasionally shrug off attacks and take shield damage instead when struck?

Perhaps a wand of "Dominion" that has the effects of all the mob controlling wands (so except immolation and ages) combined into a single scepter that can be switched modes with shift and mousewheel up/down?

I can see a really good potential in this for my modpack, considering it's got a hostile mob force with a name as it's primary aggressor which grows in power over time and stuff.

**Comment by Micmu** [comment]
Thanks for the feedback and sorry for late reply.
Yes, maybe I'll do something like this one day (make them attack, but not you). It is quite hard to account for every mob in the game (especially those with non-standard attacks, like Witches, Evokers, ...) to make them reliable companions. Simply removing all their combat AI was easy enough for this mod.
As for the inventory and combat tactics - that exceeds the scope and idea of the mod (to make fully fledged AI companions). The idea was more like to turn hostile creatures into friendly village/mansion "decorations" and simple pets. Maybe I'll do that one day (in a limited way), but no promises as I'm working on some other mod right now.

**Comment by Darkmega18** [comment]
No problem, atleast you replied. :)

and I see. I had a feeling that was the idea of it. 

If you do get to this idea would you be able to make it just for select mob with mostly standard AI? Such as zombies, skelly, husk and stray at first? Since I was hoping to make a story of such in my modpack where you eventually craft said domination scepter/tool to make your own army out of the mobs that come from the enemy of the modpack and something revolves around that, sorta "Shadow of mordor"/"Shadow of War" style and stuff.
